export { parseFigmaTree, mockText } from './figma/parser.js';
export { normalizeFigmaNode, normalizeFigmaNodes, p3TosRGB } from './figma/normalizer.js';
export { FigmaCache } from './figma/cache.js';
export { inspectDOM, setupViewport } from './dom/inspector.js';
export { mockTextContent } from './dom/mock.js';
export { normalizeDOMNode, normalizeDOMNodes, parseColor } from './dom/normalizer.js';
export { diffNodes } from './diff/engine.js';
export { compareColor, deltaE2000, colorMatch } from './diff/comparators/color.js';
export { compareLayout } from './diff/comparators/layout.js';
export { compareTypography } from './diff/comparators/typography.js';
export { compareEffects } from './diff/comparators/effects.js';
export { compareAutoLayout } from './diff/comparators/auto-layout.js';
export { hungarianMatch } from './match/matcher.js';
export { calculateScore } from './score/scorer.js';
export { aggregateScores } from './score/aggregator.js';
export { generateCLIReport } from './report/cli-report.js';
export { generateFixSuggestions } from './report/fix-suggestions.js';
export { DEFAULT_CONFIG, DEFAULT_TOLERANCES, DEFAULT_WEIGHTS } from './config.js';
export type * from './types.js';
export type { VerifyConfig, ToleranceConfig, WeightConfig } from './config.js';
